### ISSUE TITLE
The approach to great projects

### ISSUE THREAD

**Issue by nqkhanh2002** [jason-li-831202/Object-Segmentation-Web#1]
I'm just an AI student, but I'm really impressed with the projects from ADAS to here. And the Chinese are really good. Can you suggest me how to approach repos like this regarding CV. I don't know where to start, I just want to improve my ability in Computer Vision. 非常感谢

**Comment by jason-li-831202** [comment]
I suggest you can read more new research papers on CV and then consider what combination of applications can be done in these models.
